opam-version: "2.0"
version: "dev"
maintainer: [
  "Pierre Roux <pierre.roux@onera.fr>"
]

homepage: "https://github.com/math-comp/dioid"
dev-repo: "git+https://github.com/math-comp/dioid.git"
bug-reports: "https://github.com/math-comp/dioid/issues"
license: "CECILL-B"

depends: [
  "coq-core"
  "rocq-mathcomp-dioid"
]
synopsis: "Compatibility package for rocq-mathcomp-dioid"
